// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/start": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/start" | "/login" | "/signup";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/start.tsx": {
    id: "routes/start";
    page: "/start";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/start": typeof import("./app/routes/start.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
};